spring:
  rabbitmq:
    host:
    port:
    username:
    password:
    ssl:
      enabled: true # Amazon MQ에서는 SSL을 지원하는 브로커로 생성됨 (설정하지 않을 경우 브로커 접속 안됨)
  listener:
    simple:
      acknowledge-mode: manual # RabbitMQ listener에서 message가 정상적으로 처리되었다는 ack를 수동으로 보냄
